#!/bin/bash

APP_PATH="/usr/milis/ayguci/gui/ayguci-gui.py"

# Check for "socket" argument
for i in "$@"; do
  if [[ "$i" == "-s="* ]] || [[ "$i" == "--socket-id="* ]]; then
    pkexec "${APP_PATH}" "$@" || "${APP_PATH}" "$@"
    exit $?
  fi
done

pkexec "${APP_PATH}" "$@"
