milis-meson build \
-Db_lto=false \
-Db_ndebug=true \
-Dplatforms=x11,wayland \
-Ddri-drivers=i915,i965,r100,r200,nouveau \
-Dgallium-drivers=r300,r600,radeonsi,nouveau,virgl,svga,swrast,swr,iris,zink \
-Dvulkan-drivers=amd,intel,swrast \
-D vulkan-overlay-layer=true \
-D vulkan-device-select-layer=true \
-D swr-arches=avx,avx2 \
-D dri3=enabled \
-D egl=enabled \
-D gallium-extra-hud=enabled \
-D gallium-nine=enabled \
-D gallium-omx=bellagio \
-D gallium-opencl=icd \
-D gallium-va=enabled \
-D gallium-vdpau=enabled \
-D gallium-xa=enabled \
-D gallium-xvmc=disabled \
-D gbm=enabled \
-D gles1=disabled \
-D gles2=enabled \
-D glvnd=true \
-D glx=dri \
-D libunwind=enabled \
-D llvm=enabled \
-D lmsensors=enabled \
-D osmesa=gallium \
-D shared-glapi=enabled \
-D valgrind=false

ninja -C build
