export CC=gcc
export CXX=g++

cd $isim-$surum.src

mkdir build
cd build

cmake .. -G Ninja \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DLLVM_HOST_TRIPLE=$CHOST \
	-DLLVM_BUILD_LLVM_DYLIB=ON \
	-DLLVM_LINK_LLVM_DYLIB=ON \
	-DLLVM_INSTALL_UTILS=ON \
	-DLLVM_ENABLE_RTTI=ON \
	-DLLVM_ENABLE_FFI=ON \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_BUILD_DOCS=OFF \
	-DLLVM_ENABLE_SPHINX=OFF \
	-DLLVM_ENABLE_DOXYGEN=OFF \
	-DLLVM_ENABLE_OCAMLDOC=OFF \
	-DSPHINX_WARNINGS_AS_ERRORS=OFF \
	-DFFI_INCLUDE_DIR=$(pkg-config --variable=includedir libffi) \
	-DLLVM_BINUTILS_INCDIR=/usr/include
ninja all
