# from archlinux
./configure -prefix         /usr                        \
            -sysconfdir     /etc/xdg                    \
            -bindir         /usr/bin                    \
            -plugindir      /usr/lib/qt/plugins         \
            -importdir      /usr/lib/qt/imports         \
            -headerdir      /usr/include/qt             \
            -datadir        /usr/share/qt               \
            -qmldir         /usr/lib/qt/qml             \
            -archdatadir    /usr/lib/qt                 \
            -docdir         /usr/share/doc/qt           \
            -translationdir /usr/share/qt/translations  \
            -examplesdir    /usr/share/doc/qt/examples  \
            -plugin-sql-{psql,mysql,sqlite,odbc}        \
            -confirm-license    \
            -opensource         \
            -openssl-linked     \
            -nomake tests       \
            -nomake examples    \
            -optimized-qmake    \
            -reduce-relocations \
            -dbus-linked        \
            -feature-menu       \
            -feature-textdate   \
            -feature-ftp        \
            -system-zlib        \
            -system-libjpeg     \
            -system-libpng      \
            -system-harfbuzz    \
            -system-sqlite      \
            -system-freetype    \
            -no-rpath
make
