#!/bin/sh

. /etc/rc.d/functions

BIN=/usr/bin/cups-browsed

case "${1}" in
   start)
      log_info_msg "Starting cups-browsed daemon..."
      pidlist=`pidofproc $BIN`

      if [  "${?}" = "0" ]; then
        log_info_msg2 " Already running"
        log_success_msg2
        exit 0;
      fi
      # Start as background process and assume OK
      $BIN &
      log_success_msg2
      ;;

   stop)
      log_info_msg "Stopping cups-browsed daemon..."
      killproc $BIN
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc $BIN
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End BIN
